Document: down
Title: Debian down Manual
Author: <insert document author here>
Abstract: This manual describes what down is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/down/down.sgml.gz

Format: postscript
Files: /usr/share/doc/down/down.ps.gz

Format: text
Files: /usr/share/doc/down/down.text.gz

Format: HTML
Index: /usr/share/doc/down/html/index.html
Files: /usr/share/doc/down/html/*.html
